import { chmod, writeFile } from "node:fs/promises";
import { createInterface } from "node:readline/promises";
import { stdin as input, stdout as output } from "node:process";

const rl = createInterface({ input, output });
const ask = async (label) => (await rl.question(label)).trim();
const fail = (message) => { console.error(`\n設定を保存しませんでした: ${message}`); process.exitCode = 1; };

console.log("TSUMUGI ローカル接続設定（入力内容は .env.local にだけ保存され、GitHubには送られません）\n");
const site = (await ask("公開予定URL（例 https://name.github.io/repository）: ")).replace(/\/+$/, "");
const url = (await ask("Supabase Project URL: ")).replace(/\/+$/, "");
const publishable = await ask("Supabase Publishable key: ");
const service = await ask("Supabase service_role key（初回取込・バックアップ専用）: ");
rl.close();

if (!/^https:\/\/[^/]+(?:\/[^/]+)?$/i.test(site)) fail("公開URLの形式を確認してください。");
else if (!/^https:\/\/[a-z0-9-]+\.supabase\.co$/i.test(url)) fail("Supabase URLの形式を確認してください。");
else if (!publishable || !service) fail("2つのSupabaseキーは空欄にできません。");
else {
  const lines = [
    "# Generated by npm run setup:local — never commit this file.",
    `SITE_URL=${site}`,
    `SUPABASE_URL=${url}`,
    `SUPABASE_PUBLISHABLE_KEY=${publishable}`,
    `SUPABASE_SERVICE_ROLE_KEY=${service}`,
    "",
  ];
  await writeFile(".env.local", lines.join("\n"), { encoding: "utf8", mode: 0o600 });
  await chmod(".env.local", 0o600);
  console.log("\n.env.local を保存しました（Git除外済み・所有者だけが読み書き可能）。");
}

